### ISSUE TITLE
limited view:

### ISSUE THREAD

**Issue by cybector** [ILoveBacteria/ILoveBacteria.github.io#2]
![image](https://user-images.githubusercontent.com/63419902/213992145-281c8f99-2866-4a1f-8160-50d9c27c71fa.png)
based on this is all the user can see. just a fellow developer, helping another fellow developer out.

**Comment by ILoveBacteria** [comment]
Thanks for bringing this to my attention! I'll take a look and get it fixed as soon as possible.

**Comment by cybector** [comment]
**if u need anything, any help or suggestions please don't hesitate to contact me via discord brother!

CybectorTTV#165**
